
# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Add tab
    FROM python:3.7

RUN curl -s ifconfig.co/json | grep "Done" > /dev/null && \
    curl -s http://mirrors.163.com/.help/sources.list.jessie > /etc/apt/sources.list || true

RUN apt-get update;\
    apt-get install -y vim;\
    true

RUN mkdir /opt/somedir

ENV PROJECT_NAME='test'
ENV PYTHONPATH="${PYTHONPATH}:/opt/somedir"

COPY src/ /opt/somedir
WORKDIR /opt/somedir

RUN curl -s ifconfig.co/json | grep "Bla" > /dev/null && \
    pip install -r requirements.txt -i https://domain.com/simple --trusted-host domain.com || \
    pip install -r requirements.txt
